<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quasi-Experimental Design – Methods and Instruments for Data Collection</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./validity.html" rel="next">
<link href="./surveys.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Methods and Instruments for Data Collection</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Methods-and-Instruments-for-Data-Collection.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Methods-and-Instruments-for-Data-Collection.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./surveys.html">Quantitative Methods</a></li><li class="breadcrumb-item"><a href="./quasi.html">Quasi-Experimental Design</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Description of the Course</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions, Methods, and Data</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Quantitative Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Surveys</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quasi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Quasi-Experimental Design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Validity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Sources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Qualitative Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interviews.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interviews</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Case Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./focus-groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Focus Groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./trustworthiness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quality of Qualitative Research</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#to-evaluate-a-program" id="toc-to-evaluate-a-program" class="nav-link active" data-scroll-target="#to-evaluate-a-program">To evaluate a program</a></li>
  <li><a href="#what-counts-as-convincing-evidence" id="toc-what-counts-as-convincing-evidence" class="nav-link" data-scroll-target="#what-counts-as-convincing-evidence">What counts as convincing evidence?</a></li>
  <li><a href="#threats-to-validity" id="toc-threats-to-validity" class="nav-link" data-scroll-target="#threats-to-validity">Threats to validity</a></li>
  <li><a href="#experimental-design-with-random-assignment" id="toc-experimental-design-with-random-assignment" class="nav-link" data-scroll-target="#experimental-design-with-random-assignment">Experimental design with random assignment</a></li>
  <li><a href="#quasi-experimental-designs" id="toc-quasi-experimental-designs" class="nav-link" data-scroll-target="#quasi-experimental-designs">Quasi-experimental designs</a>
  <ul class="collapse">
  <li><a href="#the-nonequivalent-control-group-design" id="toc-the-nonequivalent-control-group-design" class="nav-link" data-scroll-target="#the-nonequivalent-control-group-design">The Nonequivalent Control Group Design</a></li>
  <li><a href="#time-series-designs" id="toc-time-series-designs" class="nav-link" data-scroll-target="#time-series-designs">Time series designs</a></li>
  </ul></li>
  <li><a href="#how-to-do-a-program-evaluation-using-a-quasi-experimental-design" id="toc-how-to-do-a-program-evaluation-using-a-quasi-experimental-design" class="nav-link" data-scroll-target="#how-to-do-a-program-evaluation-using-a-quasi-experimental-design">How to do a program evaluation using a quasi-experimental design</a></li>
  <li><a href="#recommended-further-reading" id="toc-recommended-further-reading" class="nav-link" data-scroll-target="#recommended-further-reading">Recommended further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./surveys.html">Quantitative Methods</a></li><li class="breadcrumb-item"><a href="./quasi.html">Quasi-Experimental Design</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Quasi-Experimental Design</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<p><strong>Required reading</strong>:</p>
<ul>
<li><p>Pages 56-61 in <span class="citation" data-cites="Cox-Ch4-2020">Cox (<a href="references.html#ref-Cox-Ch4-2020" role="doc-biblioref">2020</a>)</span> (Chapter 4 in <span class="citation" data-cites="Burkholder">Burkholder et al. (<a href="references.html#ref-Burkholder" role="doc-biblioref">2020</a>)</span>)</p></li>
<li><p><span class="citation" data-cites="Milanesi-2020">Milanesi (<a href="references.html#ref-Milanesi-2020" role="doc-biblioref">2020</a>)</span> (Chapter 17 in <span class="citation" data-cites="Burkholder">Burkholder et al. (<a href="references.html#ref-Burkholder" role="doc-biblioref">2020</a>)</span>)</p></li>
</ul>
<hr>
<section id="to-evaluate-a-program" class="level2">
<h2 class="anchored" data-anchor-id="to-evaluate-a-program">To evaluate a program</h2>
<p>In education, we often design programs to improve instruction or aspects of schooling to improve outcomes for students. Most programs cost time, money, or other limited resources.</p>
<p>Consider, for the moment, one program that perhaps you have led, implemented, inherited and maintained, or otherwise invested your attention into yourself. Inevitably the question will arise: How well is this program “working”? Do the benefits it yields outweigh the costs? These questions depend on a fundamental question which is our focus for this module:</p>
<p>What counts as evidence? How can we know?</p>
<p>When I worked in districts as the assessment director, questions of program evaluation came up many times. In many cases the originating question was, “Let’s look at the data!” and in most cases that really meant, “Some students were part of a program. Let’s look at <em>their</em> data.”</p>
<p>Often the data were scores on a common assessment of student achievement. This included districtwide assessments like DIBELS, STAR, or MAP, or the annual state assessment such as the WASL, the MSP, or the SBA. Students were often selected for a program on the basis of low pretest scores (“Level 1s” and “Level 2s”) and the outcome measure was often the same assessment given in a later testing window.</p>
<p>Favorable outcomes for this group then counted as sufficient evidence of program efficacy, and more often than not, the <em>de facto</em> evaluator was the person most invested in the program and bent on its survival or expansion (for better or worse).</p>
<p>Seldom did it occur to people (or if it did, nobody said anything) what would likely have otherwise happened to these students without experiencing the program. Were they <em>better off</em> experiencing this program than the likely alternative? What about very similar students who could have experienced this program but for whatever reason didn’t? What were their outcomes?</p>
<p>This whole discussion rests on philosophical assumptions (or commitments, or investments) that we can more or less systematically <strong>cause</strong> better student outcomes and more or less measure this causation. Put another way, it’s common to justify the merit or importance of one’s work with <strong>causal inferences</strong> that the work <strong>makes a difference</strong>.</p>
<p>Questions about how, when, on whom we collect, organize, and analyze evidence to make causal inferences are questions of <strong>research</strong> <strong>design</strong>. Design is the framework for a study.</p>
</section>
<section id="what-counts-as-convincing-evidence" class="level2">
<h2 class="anchored" data-anchor-id="what-counts-as-convincing-evidence">What counts as convincing evidence?</h2>
<p>Let’s begin by consider a hypothetical scenario of elementary reading, depicted in Table 1. Fifty third grade students score below grade level (40th percentile) on their spring SBA English Language Arts assessment. All of the students return to the same school in the fall for their fourth grade year. Half are assigned to the Innovative Reading Program while the other 25 receive Tier 1 grade level instruction. In the spring, all 50 students take the Grade 4 SBA ELA assessment.</p>
<p><strong>Table 1</strong></p>
<table class="caption-top table">
<caption><strong>Standardized Reading Achievement by Reading Program Placement</strong></caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">N</th>
<th style="text-align: center;">Pretest</th>
<th style="text-align: center;">% low income</th>
<th style="text-align: center;">Placement</th>
<th style="text-align: center;">Posttest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">24</td>
<td style="text-align: center;">2398 (40th)</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">Tier 1 Grade Level Instruction</td>
<td style="text-align: center;">2474 (50th)</td>
</tr>
<tr class="even">
<td style="text-align: center;">26</td>
<td style="text-align: center;">2401 (40th)</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">Innovative Reading Program</td>
<td style="text-align: center;">2523 (70th)</td>
</tr>
</tbody>
</table>
<p>When the scores become available shortly, they bring good news. All 50 students meet the Level 3 proficiency standard. The average scores of the 25 students in the Tier 1 grade level classroom score is 2474 (roughly the 50th percentile). They’ve all caught up to grade level. The results of the students receiving the Innovative Reading Program are even better: their average SBA score is 2523, the 70th percentile for fourth grade. Proponents of the program rejoice. “Not so fast!” cry the program critics.</p>
</section>
<section id="threats-to-validity" class="level2">
<h2 class="anchored" data-anchor-id="threats-to-validity">Threats to validity</h2>
<p>Here are their objections:</p>
<p>“Of course their scores increased! <u>Reading was a district and school focus. Everyone was talking about it last year. It was in the air</u>.” This threat to validity, an alternative explanation for the outcome of the experimental group apart from the treatment itself, is called <strong>history</strong>.</p>
<p>“Of course their scores increased! <u>Kids grow and mature anyway. Studies have shown gains in scores for kids with no formal schooling at all</u>.” This threat to validity, an alternative explanation for the outcome of the experimental group apart from the treatment itself, is called <strong>maturation</strong>.</p>
<p>“Of course their scores increased! <u>Having already taken the third grade SBA test, they knew what to expect of the test. They knew how to take it</u>.” This threat to validity, an alternative explanation for the outcome of the experimental group apart from the treatment itself, is called <strong>testing</strong>.</p>
<p>“Of course their scores increased! <u>The fourth grade SBA was easier for fourth graders than the third grade SBA was for third graders</u>.” This threat to validity is called <strong>instrumentation</strong>.</p>
<p>“Of course their scores increased! <u>Students selected on the basis of extreme low scores will always score higher on average on the posttest because extreme low scores are extreme because of the combined effects of true achievement and measurement error</u>.” This threat to validity is called <strong>statistical regression</strong>.</p>
<p>Each of these is a threat to the <strong>internal validity</strong> of a program’s treatment. Internal validity is the “basic minimum without which any experiment is uninterpretable: Did in fact the experimental treatments make a difference in this specific experimental instance?” (<span class="citation" data-cites="CampbellStanley-1963">Campbell and Stanley (<a href="references.html#ref-CampbellStanley-1963" role="doc-biblioref">1963</a>)</span>, p.&nbsp;5)</p>
<p>Critics raise a couple of additional objections:</p>
<p>“These results are limited. <u>The students selected for the program were less impacted by poverty. They had more favorable demographics. They were different students</u>!” This treat to validity is called <strong>selection bias</strong>.</p>
<p>“These results are limited. <u>The students selected for the program were able to use their advantages to learn at a faster rate</u>.” This treat to validity is called <strong>selection-maturation interaction</strong>.</p>
<p>“These results are limited. <u>The students selected for the program were sensitive to the test. They knew they had scored below standard in the spring so they tried harder the next year</u>.” This threat to validity is called <strong>reactive</strong> or <strong>interaction effect of testing</strong>.&nbsp;</p>
<p>“These results are limited. <u>The students selected for the program had been low and received more attention and knew that we’re watching them closely</u>.” This threat to validity is called <strong>multiple-treatment interference</strong>.</p>
<p>These are threats to the <strong>external validity</strong> of a program’s treatment.&nbsp;External validity “asks the question of generalizability: To what populations, settings, treatment variables, and measurement variables can this effect be generalized?” Threats to external validity limit the generalizability of the results to broader populations.</p>
<p>What do you make of these objections, in light of the data and what you know of the design of the treatment? Are some more credible than others?</p>
</section>
<section id="experimental-design-with-random-assignment" class="level2">
<h2 class="anchored" data-anchor-id="experimental-design-with-random-assignment">Experimental design with random assignment</h2>
<p>The argument for the program is that it dramatically helps struggling readers, which is to say, struggling readers are <em>better off</em> in the program compared similar students in Tier 1 classroom instruction. This is because similar students did not gain as much as students in the program. The argument thus hinges on the similarity of the two groups. Any alternative explanation for the improvement of the experimental group must apply to the comparison group.</p>
<p>What if these students were assigned randomly to the conditions? This would have the effect of rendering pre-existing differences not statistically significant (that is, their differences were no more than we would expect to see by chance) … by design. This would strengthen the program advocates’ causal argument that (1) they were all the same students and (2) the program worked better than Tier 1 instruction.</p>
<p>Now it is probably wise to let go of it. Assuming we were so inclined, it is seldom feasible to prospectively randomly assign students to conditions, or to keep treatments so cleanly isolated, in real schools, districts, and dioceses. <strong>Nor will it be possible for you to fully design and carry out a prospective experimental design with random assignment in your current doctoral program</strong>.</p>
</section>
<section id="quasi-experimental-designs" class="level2">
<h2 class="anchored" data-anchor-id="quasi-experimental-designs">Quasi-experimental designs</h2>
<p>In lieu of a true experimental design, consider adding quasi-experimental designs to your toolbox. These are frameworks for collecting, organizing, and analyzing (primarily quantitative) data for causal inference – such as for program evaluation – that fall short of pure experimental design with random assignment, and therefore expose the evaluation to criticism. As Cox (in <span class="citation" data-cites="Burkholder">Burkholder et al. (<a href="references.html#ref-Burkholder" role="doc-biblioref">2020</a>)</span>, 56) puts it well: “The lack of random assignment in quasi-experimental designs means that the groups may not initially be equal or similar. This presents the challenge of ruling out other alternative explanations that could be responsible for any observed outcome.” Quasi-experimental designs use one or more work-arounds to mitigate various inescapable threats to validity. Consider the following three:</p>
<section id="the-nonequivalent-control-group-design" class="level3">
<h3 class="anchored" data-anchor-id="the-nonequivalent-control-group-design">The Nonequivalent Control Group Design</h3>
<p>This design comes from <span class="citation" data-cites="CampbellStanley-1963">Campbell and Stanley (<a href="references.html#ref-CampbellStanley-1963" role="doc-biblioref">1963</a>)</span>, who, at that time, claimed:</p>
<blockquote class="blockquote">
<p>one of the most widespread experimental designs in educational research involves an experimental group and a control group both given a pretest and a posttest, but in which the control group and the experimental group do not have pre-experimental sampling equivalence. Rather, the groups constitute naturally assembled collectives such as classrooms, as similar as availability permits but yet not so similar that one can dispense with the pretest. (p.&nbsp;17)</p>
</blockquote>
<p><span class="citation" data-cites="CookCampbell-1979">Cook and Campbell (<a href="references.html#ref-CookCampbell-1979" role="doc-biblioref">1979</a>)</span> later saw the design as “perhaps the most frequently used design in social science research and is fortunately often interpretable. It can, therefore, be recommended in situations where nothing better is available” (103-4).</p>
<p>Here is the design, and it is the design of the hypothetical example above:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">O</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">O</td>
</tr>
<tr class="even">
<td style="text-align: center;">O</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">O</td>
</tr>
</tbody>
</table>
<p>The design overcomes several of the critics’ objections raised above.</p>
<p>History, maturation, testing, and instrumentation are less credible objections because each of these explanations would apply to both groups, and the students in the experimental classroom still outperformed their peers in the comparison classroom. Notice here the added value of a comparison group!</p>
<p>Statistical regression is a valid criticism any time students are selected for a treatment on the basis of extreme scores, because extremely low or high pretest scores will always, on average, regress to the mean on any retest. This should be less of a problem if both groups were selected on the same set of extreme pretest scores.</p>
<p>Interactions between pretesting, selection, maturation, and the experimental treatment mean the students selected for the treatment were aware of their selection and reacted to it. This could be a valid threat whenever students selected for a program become aware of it, especially by virtue of contact with comparison students.</p>
</section>
<section id="time-series-designs" class="level3">
<h3 class="anchored" data-anchor-id="time-series-designs">Time series designs</h3>
<p>A time series design is, essentially, “the presence of a periodic measurement process on some group or individual and the introduction of an experimental change into this time series of measurements, the results of which are indicated by a discontinuity in the measurements recorded in the time series” (<span class="citation" data-cites="CampbellStanley-1963">Campbell and Stanley (<a href="references.html#ref-CampbellStanley-1963" role="doc-biblioref">1963</a>)</span>, 37).</p>
<p>One familiar application of this design might be annual trends in proficiency rates (or average scores) for a grade level at a school.</p>
<section id="one-group-design" class="level4">
<h4 class="anchored" data-anchor-id="one-group-design">One group design</h4>
<p>A time series design for one group looks like this…</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">O<sub>1</sub></td>
<td style="text-align: center;">O<sub>2</sub></td>
<td style="text-align: center;">O<sub>3</sub></td>
<td style="text-align: center;">O<sub>4</sub></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">O<sub>5</sub></td>
<td style="text-align: center;">O<sub>6</sub></td>
<td style="text-align: center;">O<sub>7</sub></td>
<td style="text-align: center;">O<sub>8</sub></td>
</tr>
</tbody>
</table>
<p>…and a simple line graph of eight years of results with an intervention between Time 4 and 5 might look like this:</p>
<p><img src="assets/time-series-one.png" class="img-fluid"></p>
<p>What’s going on here? What do we make of these results?</p>
<p>Advocates of the intervention will hail the improvement in scores as evidence of effectiveness.</p>
<p>Are we convinced? What might be some credible threats to validity?</p>
<p>Unless the case is somewhat isolated, this design may be vulnerable to <strong>history</strong> as a rival explanation. An external event could have caused the observed increase.</p>
<p><strong>Maturation</strong> could be a rival explanation if the trend looks like what we would expect of human development, although some kinds of development can probably occur in stages.</p>
<p><strong>Testing</strong> is not likely a rival explanation if the same test was used for all observations. It could be a rival explanation if Times 5 through 8 used a different test. This is often an issue in public education when states, districts, and schools adopt different tests from time to time, which gives rise to a saying: “If you want to measure change, don’t change the measure.”</p>
<p><strong>Regression</strong> is not a rival explanation because none of the pretest scores began at the extremes.</p>
</section>
<section id="multiple-group-design" class="level4">
<h4 class="anchored" data-anchor-id="multiple-group-design">Multiple-group design</h4>
<p>A multiple-group design, as you might imagine, adds groups to the design, like this:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">O<sub>1</sub></td>
<td style="text-align: center;">O<sub>2</sub></td>
<td style="text-align: center;">O<sub>3</sub></td>
<td style="text-align: center;">O<sub>4</sub></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">O<sub>5</sub></td>
<td style="text-align: center;">O<sub>6</sub></td>
<td style="text-align: center;">O<sub>7</sub></td>
<td style="text-align: center;">O<sub>8</sub></td>
</tr>
<tr class="even">
<td style="text-align: center;">O<sub>1</sub></td>
<td style="text-align: center;">O<sub>2</sub></td>
<td style="text-align: center;">O<sub>3</sub></td>
<td style="text-align: center;">O<sub>4</sub></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">O<sub>5</sub></td>
<td style="text-align: center;">O<sub>6</sub></td>
<td style="text-align: center;">O<sub>7</sub></td>
<td style="text-align: center;">O<sub>8</sub></td>
</tr>
</tbody>
</table>
<p>Imagine six groups – in this case, schools, – all with the same time series of observations. Imagine an intervention – such as additional discretionary funding, or an additional 1.0 FTE to support struggling learners – that all received or experienced at the same time. A line graph of their results might look like this:</p>
<p><img src="assets/time-series.png" class="img-fluid"></p>
<p>Once again, improvements since the intervention might look like evidence of the intervention’s effectiveness. But more data on either side of the intervention provides context. In schools that were already improving before the intervention, it is more difficult to attribute the improvement to the intervention.</p>
<p>School-level trends in annual aggregate test scores are messy. A school implementing an intervention might be able to find schools with comparable demographics to use as controls. But those schools might be doing their own interventions.</p>
<p>Seldom do we have so much longitudinal data. More often we have maybe a few years of data, say O<sub>4</sub> and O<sub>5</sub>, or Time 4 and Time 5, which is essentially the Nonequivalent Control Groups Design. In those cases, improvements in scores fall prey to many of the threats to validity outlined above. A time series provides more context and more follow-up.</p>
</section>
<section id="moral-of-the-story" class="level4">
<h4 class="anchored" data-anchor-id="moral-of-the-story">Moral of the Story</h4>
<p>Admittedly I’ve expressed the aforementioned discussion of designs in very abstract, technical terms drawn straight from the methodological literature on this topic (<span class="citation" data-cites="CampbellStanley-1963">Campbell and Stanley (<a href="references.html#ref-CampbellStanley-1963" role="doc-biblioref">1963</a>)</span>; <span class="citation" data-cites="CookCampbell-1979">Cook and Campbell (<a href="references.html#ref-CookCampbell-1979" role="doc-biblioref">1979</a>)</span>; <span class="citation" data-cites="Shadish-2002">Shadish, Cook, and Campbell (<a href="references.html#ref-Shadish-2002" role="doc-biblioref">2002</a>)</span>).</p>
<p>My intent is far less for you to adopt this language than to understand how this comparative causal logic can apply to programs in your context and/or that have captured your interest and attention.</p>
<p>Compare the Nonequivalent Control Group Design with the Single- and Multiple-Group Time Series Designs. Can you see how much is gained with the addition of groups and measurements on either side of the intervention?</p>
</section>
</section>
</section>
<section id="how-to-do-a-program-evaluation-using-a-quasi-experimental-design" class="level2">
<h2 class="anchored" data-anchor-id="how-to-do-a-program-evaluation-using-a-quasi-experimental-design">How to do a program evaluation using a quasi-experimental design</h2>
<p>To carry out a retrospective analysis of existing quantitative data using quasi-experimental design for the purpose of program evaluation, you need:</p>
<ul>
<li><p>A group of schools, or students, or people who experienced some initiative, program, intervention, or treatment of interest at a measurable point in time</p></li>
<li><p>A comparison group of similar schools, students, or people who did not experience the program or treatment of interest</p></li>
<li><p>Some pretest data, to establish baseline differences. Maybe these pretest data were the basis for assignment to the initiative or program</p></li>
<li><p>Some demographic data, to explore differences between the groups besides the treatment</p></li>
<li><p>Some posttest data, to establish outcomes of both groups. Ideally the pretest and posttest are the same interest, but this is not required.</p></li>
</ul>
<p>Concretely, all this means:</p>
<ul>
<li><p>Excel or other spreadsheet software, and in your worksheets you need:</p></li>
<li><p>A column of pretest scores on a population of schools or students</p></li>
<li><p>Columns for demographic variables on this population of schools or students (gender, race, low income, English language proficiency)</p></li>
<li><p>A column designating which schools or students participated in the initiative or program. Code the schoosl/students receiving the initiative/program as 1, all others 0.</p></li>
<li><p>A column of posttest scores on this population If these data are coming from different places then you need some kind of key variable (such as an ID number) that is common across all the different data sources which you can use to match the data together</p></li>
</ul>
<p>Your end game is one spreadsheet where all of these variables are together in one place. Then you can use PivotTable to summarize the data.&nbsp;<u>Keep checking back here for a sample Excel file as a guide</u>.</p>
</section>
<section id="recommended-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="recommended-further-reading">Recommended further reading</h2>
<p>If your current or future work casts you in the role of program evaluator, it may help you to have some additional readings in your library for reference. Here are the three classic texts on experimental, quasi-experimental, and non-experimental design. I personally own and highly recommend all three.</p>
<p>Campbell, D. T., &amp; J. C. Stanley. 1963. Experimental and Quasi-Experimental Designs for Research. Houghton-Mifflin: Boston.</p>
<p>Cook, T.D., &amp; D.T. Campbell. 1979. Quasi-Experimentation: Design and Analysis Issues for Field Settings. Houghton Mifflin: Boston.</p>
<p>Shadish, W. R.., Cook, T. D., &amp; J.S. Campbell. 2002. Experimental and Quasi-Experimental Designs for Generalized Causal Inference. Houghton Mifflin: Boston.</p>
<hr>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Burkholder" class="csl-entry" role="listitem">
Burkholder, G. J., K. A. Cox, L. M. Crawford, and Hitchcock. 2020. <em>Research Design and Methods: An Applied Guide for the Scholar-Practitioner</em>. Sage.
</div>
<div id="ref-CampbellStanley-1963" class="csl-entry" role="listitem">
Campbell, D. T., and J. C. Stanley. 1963. <em>Experimental and Quasi-Experimental Designs for Research</em>. Houghton-Mifflin.
</div>
<div id="ref-CookCampbell-1979" class="csl-entry" role="listitem">
Cook, T. D, and D. T. Campbell. 1979. <em>Quasi-Experimentation: Design and Analysis Issues for Field Settings</em>. Houghton-Mifflin.
</div>
<div id="ref-Cox-Ch4-2020" class="csl-entry" role="listitem">
Cox, Kimberley A. 2020. <span>“Quantitative Research Designs.”</span> In <em>Research Design and Methods: An Applied Guide for the Scholar-Practitioner</em>, edited by Gary J. Burkholder, Kimberley A. Cox, Linda M. Crawford, and John H. Hitchcock, 51–65. Sage Publications.
</div>
<div id="ref-Milanesi-2020" class="csl-entry" role="listitem">
Milanesi, Louis. 2020. <span>“Program Evaluation.”</span> In <em>Research Design and Methods: An Applied Guide for the Scholar-Practitioner</em>, edited by Gary J. Burkholder, Kimberley A. Cox, Linda M. Crawford, and John H. Hitchcock, 259–74. Sage Publications.
</div>
<div id="ref-Shadish-2002" class="csl-entry" role="listitem">
Shadish, W. R., T. D. Cook, and J. S. Campbell. 2002. <em>Experimental and Quasi-Experimental Designs for Generalized Causal Inference</em>. Houghton-Mifflin.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/edld704\.jackhuber\.org");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./surveys.html" class="pagination-link" aria-label="Surveys">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Surveys</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./validity.html" class="pagination-link" aria-label="Validity">
        <span class="nav-page-text">Validity</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>